#!/usr/bin/env bash
# pb-hcf SessionStart hook — inject HCF v2 hook discovery into Claude context.
#
# Bypasses the "Claude improvises buggy bash" failure mode by giving HCF's
# plan-create a known-good enumeration to read directly from session context,
# so it never has to run a glob loop itself. See feedback memory
# `feedback_hcf_discovery_non_deterministic.md` for the PPS 2026-06-30 cause.
#
# Fires silently (exit 0, no output) when:
#   - discover-hooks.sh is not executable
#   - target directory not found (CWD is not a project root)
#   - python3 missing (used for JSON escaping)

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DISCOVERY="$DIR/../scripts/discover-hooks.sh"

[[ -x "$DISCOVERY" ]] || exit 0
command -v python3 >/dev/null 2>&1 || exit 0

OUTPUT=$("$DISCOVERY" 2>/dev/null) || exit 0
[[ -z "$OUTPUT" ]] && exit 0

python3 -c "
import json, sys
out = sys.stdin.read()
msg = (
    'pb-hcf hook enrollment discovery (deterministic — generated by the '
    'pb-hcf SessionStart hook from scripts/discover-hooks.sh). When HCF\\'s '
    'plan-create or plan-orchestrate reaches a hook firing step, treat this '
    'as the authoritative resolved-order list — do NOT improvise a bash glob '
    'enumeration (which has been observed to crash silently and produce false '
    'empty-hook results — see PPS 2026-06-30 scrollback for the exact failure '
    'mode). Spawn agents per the table below.\\n\\n' + out
)
print(json.dumps({'hookSpecificOutput': {'hookEventName': 'SessionStart', 'additionalContext': msg}}))
" <<< "$OUTPUT"
